name: Trigger deploy for web1 after 1 min

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Wait & Deploy to Vercel
    runs-on: ubuntu-latest
    environment: tofu-production

    strategy:
      fail-fast: false
      matrix:
        app: [web1]
        env: [production]

    steps:
      - name: Wait 1 minute before deploying
        run: sleep 20

      - name: Checkout
        uses: actions/checkout@v4

      - name: Gathering Tofu Output
        uses: dflook/tofu-output@v2
        id: tf-outputs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_INPUT: "0"
          VERCEL_API_TOKEN: ${{ secrets.PLAN_SECRETS_VERCEL_API_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_passphrase: ${{ secrets.TF_VAR_PASSPHRASE }}
        with:
          path: .infrastructure/${{ matrix.app }}
          backend_config: ../common/_backend_config.tfvars
          var_file: .infrastructure/${{ matrix.app }}/env/${{ matrix.env }}.tfvars

      - name: Trigger Vercel Deploy Hook
        run: |
          curl -s -X POST "${{ steps.tf-outputs.outputs.tofu_web1_deploy_hook_url }}" \
            --fail \
            --show-error
